%%
%% Autogenerated by Thrift Compiler (0.8.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(mtc_schema_types).

-include("mtc_schema_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('mt_comment') ->
  {struct, [{1, i32}, {2, string}, {3, string}, {4, i64}, {5, string}, {6, string}, {7, {list, i32}}]}
;

struct_info('mt_post') ->
  {struct, [{1, i64}, {2, string}, {3, string}, {4, i64}, {5, string}, {6, string}, {7, i32}, {8, {list, {struct, {'mtc_schema_types', 'mt_comment'}}}}]}
;

struct_info('mt_person') ->
  {struct, [{1, i32}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('mt_comment') ->
  {struct, [{1, undefined, i32, 'id', 0}, {2, undefined, string, 'author', undefined}, {3, undefined, string, 'body', undefined}, {4, undefined, i64, 'timestamp', undefined}, {5, optional, string, 'origin', undefined}, {6, optional, string, 'client', undefined}, {7, undefined, {list, i32}, 'parents', []}]}
;

struct_info_ext('mt_post') ->
  {struct, [{1, undefined, i64, 'id', 0}, {2, undefined, string, 'author', undefined}, {3, undefined, string, 'body', undefined}, {4, undefined, i64, 'timestamp', undefined}, {5, optional, string, 'origin', undefined}, {6, optional, string, 'client', undefined}, {7, undefined, i32, 'comment_cnt', 0}, {8, undefined, {list, {struct, {'mtc_schema_types', 'mt_comment'}}}, 'comments', []}]}
;

struct_info_ext('mt_person') ->
  {struct, [{1, undefined, i32, 'id', 0}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

